server:
  port: 8082
  servlet:
    contextPath: /cnc

spring:
  datasource:
    url: jdbc:postgresql://database:5432/sos
    username: postgres
    password: postgres
    
org.n52.stream:
  sosendpoint: http://sos:8080/52n-sos-webapp/service
  dataflowhost: http://dataflow:9393
  baseurl: http://cnc:8082/cnc
  datasource:
    url: jdbc:postgresql://database:5432/sos
    username: postgres
    password: postgres