spring:
  application:
    name: csv-timestamp-filter

  cloud:
    stream:
      bindings:
        input:
          group: haliho
          destination: demo
        output:
          group: haliho
          destination: log

server:
  port: 8083

org.n52.stream:
  last-seen-timestamp:
  column-separator: ";"
  date-column-index: 0
  time-column-index: 1
  date-column-format: "dd.MM.yy"
  time-column-format: "HH:mm"

logging:
  level:
    org.n52.stream.seadatacloud.processors: TRACE
