spring:
  application:
    name: processor-app

  cloud:
    stream:
      bindings:
        input:
          group: haliho
          destination: demo
        output:
          group: haliho
          destination: log

server:
  port: 8083

processor:
  ctd:
    topic: spiddal-ctd
    feature-id: "Galway Bay Cable Observatory"
  weather:
    topic: airmar-rinville-1
    feature-id: "Galway Bay Cable Observatory"
  fluorometer:
    topic: spiddal-fluorometer
    feature-id: "Galway Bay Cable Observatory"

