spring:
  application:
    name: processor-app

  cloud:
    stream:
      bindings:
        input:
          group: haliho
          destination: demo
        output:
          group: haliho
          destination: log

server:
  port: 8083

org.n52.stream:
  sensorml-url: http://localhost:8080/AggregateProcess.xml
  offering: example-offering
  sensor: example-sensor

logging:
  level:
    org.n52.stream.seadatacloud.marine: TRACE
